AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for Glue ETL Job

Parameters:
  Environment:
    Type: String
    Description: Environment
    Default: dev
    AllowedValues:
      - dev
      - prod

  GlueJobName:
    Type: String
    Description: Glue Job Name
    Default: dev-glue-job

  ArtifactBucket:
    Type: String
    Description: S3 Bucket for Glue Job Artifacts
    Default: dev-glue-artifacts

Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJobName
      Role: !GetAtt GlueJobRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub s3://${ArtifactBucket}/glue.py
      DefaultArguments:
        "--TempDir": !Sub s3://${ArtifactBucket}/temp
        "--enable-metrics": ""
      GlueVersion: 2.0
      MaxCapacity: 2
      MaxRetries: 0
      NumberOfWorkers: 2
      WorkerType: G.1X
    DependsOn:
      - GlueJobRole


  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${GlueJobName}-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: !Sub ${GlueJobName}-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactBucket}/*
                  - !Sub arn:aws:s3:::${ArtifactBucket}
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'glue:GetJobRun'
                  - 'glue:GetJobRuns'
                  - 'glue:GetJobs'
                  - 'glue:GetJob'
                  - 'glue:StartJobRun'
                  - 'glue:BatchStopJobRun'
                  - 'glue:UpdateJob'
                  - 'glue:DeleteJob'
                  - 'glue:GetJobBookmark'
                  - 'glue:GetTriggers'
                  - 'glue:GetTrigger'
                  - 'glue:CreateTrigger'
                  - 'glue:UpdateTrigger'
                  - 'glue:DeleteTrigger'
                  - 'glue:StartTrigger'
                  - 'glue:BatchStopTrigger'
                  - 'glue:GetTriggerRuns'
                  - 'glue:GetTriggerRun'
                  - 'glue:BatchGetTriggers'
                  - 'glue:CreateJob'
                  - 'glue:BatchDeleteConnection'
                  - 'glue:BatchCreatePartition'
                  - 'glue:BatchDeletePartition'
                  - 'glue:BatchGetPartition'
                  - 'glue:CreateConnection'
                  - 'glue:DeleteConnection'
                  - 'glue:GetConnection'
                  - 'glue:GetConnections'
                  - 'glue:UpdateConnection'
                  - 'glue:CreateDatabase'
                  - 'glue:DeleteDatabase'
                  - 'glue:GetDatabase'
                  - 'glue:GetDatabases'
                  - 'glue:UpdateDatabase'
                  - 'glue:CreateTable'
                  - 'glue:DeleteTable'
                  - 'glue:BatchDeleteTable'
                  - 'glue:UpdateTable'
                  - 'glue:GetTable'
                  - 'glue:GetTables'
                  - 'glue:BatchCreatePartition'
                  - 'glue:BatchDeletePartition'
                  - 'glue:BatchGetPartition'
                  - 'glue:BatchGetTriggers'
                  - 'glue:BatchStopTrigger'
                  - 'glue:CreateTrigger'
                  - 'glue:DeleteTrigger'
                  - 'glue:GetTrigger'
                  - 'glue:GetTriggers'
                  - 'glue:StartTrigger'
                  - 'glue:UpdateTrigger'
                  - 'glue:BatchCreatePartition'
                  

                
                Resource: '*'
